Add IPv6 support
infrawatch/sg-bridge pull request #37
Opened 2024-05-28 15:17 UTC by paramite

This patch makes bridge accept IPv6 addresses as amqp_url value.

2024-05-28 15:43 UTC, csibbitt approved these changes
This LGTM but I'd like to know it's tested before we merge.

2024-05-29 07:24 UTC, vkmc commented
recheck

2024-05-29 13:07 UTC, vkmc commented
There is some recurring failure in the CI, not related to the timeouts. It seems that the bridge container is constantly failing. See for example https://review.rdoproject.org/zuul/build/e7227852b3a747bf857a1168dddc1c71/log/controller/controller/post_oc_describe_pod_default-cloud1-ceil-event-smartgateway-7b5d4fcd79-5fswr.log in the [stf-crc-ocp_414-local_build](https://review.rdoproject.org/zuul/build/e7227852b3a747bf857a1168dddc1c71). We don't really have access to the container logs IIRC.

2024-05-29 13:09 UTC, vkmc requested changes
Seems there is something wrong when trying to start the smart-gateway with this change.

2024-05-29 19:35 UTC, csibbitt commented on tests.c
> +#include "utils.h"
Without this I get the following compile problem:

```
gcc -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -c -o test_obj/tests.o tests.c
tests.c: In function ‘test_match_amqp_url_hostname’:
tests.c:26:5: error: implicit declaration of function ‘match_regex’ [-Wimplicit-function-declaration]
   26 |     match_regex(AMQP_URL_REGEX, matches, 10,
      |     ^~~~~~~~~~~
make: *** [Makefile:94: test_obj/tests.o] Error 1
```

2024-05-29 19:57 UTC, vyzigold commented
The ending of the new regex is the cause of the CI failures. It seems the "[^\\s]" doesn't work as intended instead of matching "non-whitespace" it seems to match "non-'s' character".  And because we use "s" in the address in the CI, it fails. Otherwise an impressive work. Thank you.

2024-05-29 20:12 UTC, csibbitt commented
> The ending of the new regex is the cause of the CI failures. It seems the "[^\\s]" doesn't work as intended instead of matching "non-whitespace" it seems to match "non-'s' character". And because we use "s" in the address in the CI, it fails. Otherwise an impressive work. Thank you.

I reproduced this locally, if I change /baz to /bas in a unit test I get a segfault instead of a pass. :)

2024-05-29 20:20 UTC, csibbitt approved these changes

2024-05-29 20:20 UTC, csibbitt commented on bridge.c
> +        app.amqp_con.user = strdup(matches[3]);
Good find! This is an old bug that we should have caught in the initial review years ago.

2024-05-30 11:15 UTC, paramite commented on tests.c
> +#include "utils.h"
Yes you need utils as I moved match_regex there to be able to include it both in bridge.c and tests.c and not conflict with two main functions.

2024-05-30 12:25 UTC, paramite commented
recheck

2024-05-30 14:16 UTC, paramite commented
recheck

2024-05-31 06:55 UTC, vkmc commented
recheck

2024-05-31 09:01 UTC, vkmc approved these changes
Code looks good, and thanks so much for enhancing test coverage and automation as well!

2024-05-31 09:06 UTC, merged